[package]
name = "db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow            = "1"
cloud-storage     = "0"
deadpool-postgres = "0"
deadpool-redis    = "0"
openssl           = "0"
postgres-openssl  = "0"
serde             = { version = "1", features = ["derive"] }
serde_derive      = "1"
serde_json        = "1"
tokio             = { version = "1", default-features = false, features = ["rt-multi-thread"] }
tokio-postgres    = { version = "0", features = ["with-chrono-0_4","with-serde_json-1"] }
